
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - pictures  # Change this if your default branch is different

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Modify this if your build command is different

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: dist  # The output folder of your build (change if needed)